services:
  backend:
    build:
      context: ./pkgs/backend
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - "4452:3000"
  influxdb:
    image: influxdb:latest
    volumes:
      - ./influxdb/data:/var/lib/influxdb2:rw
    env_file: .env
    ports:
      - 4451:8086
    restart: unless-stopped
